export const industryTemplates = [
  {
    id: "manufacturing",
    name: "Manufacturing",
    industry: "manufacturing",
    description: "Equipment, tooling, line changeover, maintenance, labor, and waste costs",
    costItems: [
      { name: "Current Direct Labor", type: "opex", amount: 15000, frequency: "monthly", costPhase: "current_state", description: "Current production floor labor costs" },
      { name: "Current Maintenance", type: "opex", amount: 5000, frequency: "monthly", costPhase: "current_state", description: "Current equipment maintenance costs" },
      { name: "Current Scrap & Waste", type: "opex", amount: 3000, frequency: "monthly", costPhase: "current_state", description: "Current material waste and scrap" },
      { name: "Future Direct Labor", type: "opex", amount: 12000, frequency: "monthly", costPhase: "future_state", description: "Optimized production floor labor costs" },
      { name: "Future Maintenance", type: "opex", amount: 4000, frequency: "monthly", costPhase: "future_state", description: "Reduced equipment maintenance costs" },
      { name: "Future Scrap & Waste", type: "opex", amount: 1500, frequency: "monthly", costPhase: "future_state", description: "Reduced material waste and scrap" },
      { name: "Equipment Purchase", type: "capex", amount: 500000, frequency: "once", depreciationYears: 10, costPhase: "project_cost", description: "Primary manufacturing equipment" },
      { name: "Tooling & Dies", type: "capex", amount: 75000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "Specialized tooling and dies" },
      { name: "Line Changeover", type: "transition", amount: 50000, frequency: "once", costPhase: "project_cost", description: "Production line reconfiguration" },
    ],
    valueDrivers: [
      { name: "Unit Cost Reduction", type: "cost_reduction", annualValue: 120000, confidenceLevel: "high", monthsToRealize: 3, description: "Lower per-unit production cost from automation" },
      { name: "Throughput / OEE Improvement", type: "productivity", annualValue: 200000, confidenceLevel: "medium", monthsToRealize: 6, description: "Increased output with same resources" },
      { name: "Scrap & Rework Reduction", type: "cost_reduction", annualValue: 36000, confidenceLevel: "high", monthsToRealize: 2, description: "Less material waste and fewer defective units" },
      { name: "Labor Productivity Gain", type: "productivity", annualValue: 80000, confidenceLevel: "medium", monthsToRealize: 4, description: "More output per labor hour" },
    ],
  },
  {
    id: "retail",
    name: "Retail",
    industry: "retail",
    description: "Inventory, shrinkage, store labor, POS systems, and logistics",
    costItems: [
      { name: "Current Store Labor", type: "opex", amount: 12000, frequency: "monthly", costPhase: "current_state", description: "Current retail staff wages" },
      { name: "Current Inventory Shrinkage", type: "opex", amount: 2500, frequency: "monthly", costPhase: "current_state", description: "Current theft, damage, admin errors" },
      { name: "Current Logistics", type: "opex", amount: 8000, frequency: "monthly", costPhase: "current_state", description: "Current distribution and delivery costs" },
      { name: "Future Store Labor", type: "opex", amount: 10000, frequency: "monthly", costPhase: "future_state", description: "Optimized retail staff wages" },
      { name: "Future Inventory Shrinkage", type: "opex", amount: 1200, frequency: "monthly", costPhase: "future_state", description: "Reduced shrinkage with new controls" },
      { name: "Future Logistics", type: "escalating", amount: 7000, frequency: "monthly", escalationRate: 4, costPhase: "future_state", description: "Optimized distribution costs" },
      { name: "Initial Inventory", type: "one_time", amount: 200000, frequency: "once", costPhase: "project_cost", description: "Initial stock purchase" },
      { name: "POS System", type: "capex", amount: 25000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "Point of sale hardware and software" },
      { name: "Store Setup", type: "transition", amount: 75000, frequency: "once", costPhase: "project_cost", description: "Store buildout and fixtures" },
    ],
    valueDrivers: [
      { name: "Shrinkage Reduction", type: "cost_reduction", annualValue: 30000, confidenceLevel: "high", monthsToRealize: 2, description: "Reduced inventory loss through better controls" },
      { name: "Inventory Turnover Improvement", type: "productivity", annualValue: 50000, confidenceLevel: "medium", monthsToRealize: 6, description: "Faster stock rotation and less dead inventory" },
      { name: "Conversion Rate Improvement", type: "revenue", annualValue: 80000, confidenceLevel: "medium", monthsToRealize: 4, description: "Higher percentage of visitors making purchases" },
      { name: "Average Basket Size Increase", type: "revenue", annualValue: 45000, confidenceLevel: "low", monthsToRealize: 6, description: "Upselling and cross-selling improvements" },
    ],
  },
  {
    id: "saas",
    name: "SaaS / Software",
    industry: "saas",
    description: "Licensing, infrastructure, implementation, training, and support",
    costItems: [
      { name: "Current Software Licensing", type: "opex", amount: 8000, frequency: "monthly", costPhase: "current_state", description: "Current legacy software subscription fees" },
      { name: "Current Cloud Infrastructure", type: "opex", amount: 4000, frequency: "monthly", costPhase: "current_state", description: "Current hosting and infrastructure costs" },
      { name: "Current Support Costs", type: "opex", amount: 3000, frequency: "monthly", costPhase: "current_state", description: "Current technical support burden" },
      { name: "Future Software Licensing", type: "opex", amount: 5000, frequency: "monthly", costPhase: "future_state", description: "New SaaS subscription fees" },
      { name: "Future Cloud Infrastructure", type: "opex", amount: 3000, frequency: "monthly", costPhase: "future_state", description: "Optimized hosting costs" },
      { name: "Future Support & Maintenance", type: "escalating", amount: 2000, frequency: "monthly", escalationRate: 5, costPhase: "future_state", description: "Ongoing technical support" },
      { name: "Implementation", type: "one_time", amount: 100000, frequency: "once", costPhase: "project_cost", description: "Initial setup and configuration" },
      { name: "Training", type: "transition", amount: 25000, frequency: "once", costPhase: "project_cost", description: "User training and onboarding" },
      { name: "Data Migration", type: "transition", amount: 30000, frequency: "once", costPhase: "project_cost", description: "Migration from legacy systems" },
    ],
    valueDrivers: [
      { name: "Customer Churn Reduction", type: "revenue", annualValue: 150000, confidenceLevel: "medium", monthsToRealize: 6, description: "Retaining more customers through better product experience" },
      { name: "CAC Improvement", type: "cost_reduction", annualValue: 60000, confidenceLevel: "medium", monthsToRealize: 4, description: "Lower customer acquisition cost through better tooling" },
      { name: "Support Ticket Deflection", type: "productivity", annualValue: 40000, confidenceLevel: "high", monthsToRealize: 3, description: "Self-service and automation reducing support volume" },
      { name: "Upsell / Expansion Revenue", type: "revenue", annualValue: 100000, confidenceLevel: "low", monthsToRealize: 9, description: "Increased revenue from existing customer base" },
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    industry: "healthcare",
    description: "Compliance, EHR systems, staffing, and regulatory filings",
    costItems: [
      { name: "Current Compliance & Audit", type: "opex", amount: 10000, frequency: "monthly", costPhase: "current_state", description: "Current HIPAA compliance and auditing costs" },
      { name: "Current Clinical Staffing", type: "opex", amount: 25000, frequency: "monthly", costPhase: "current_state", description: "Current healthcare professional wages" },
      { name: "Current Insurance Premiums", type: "opex", amount: 10000, frequency: "monthly", costPhase: "current_state", description: "Current malpractice and liability insurance" },
      { name: "Future Compliance & Audit", type: "opex", amount: 8000, frequency: "monthly", costPhase: "future_state", description: "Streamlined compliance with new EHR" },
      { name: "Future Clinical Staffing", type: "opex", amount: 22000, frequency: "monthly", costPhase: "future_state", description: "Optimized staffing with better tools" },
      { name: "Future Insurance Premiums", type: "escalating", amount: 9000, frequency: "monthly", escalationRate: 6, costPhase: "future_state", description: "Slightly reduced insurance costs" },
      { name: "EHR System", type: "capex", amount: 300000, frequency: "once", depreciationYears: 7, costPhase: "project_cost", description: "Electronic Health Records system" },
      { name: "Staff Training", type: "transition", amount: 40000, frequency: "once", costPhase: "project_cost", description: "Clinical staff training programs" },
      { name: "Regulatory Filings", type: "opex", amount: 5000, frequency: "annually", costPhase: "project_cost", description: "Annual regulatory submissions" },
    ],
    valueDrivers: [
      { name: "Billing Error Reduction", type: "cost_reduction", annualValue: 90000, confidenceLevel: "high", monthsToRealize: 3, description: "Fewer billing mistakes reducing revenue leakage" },
      { name: "Patient Throughput Increase", type: "revenue", annualValue: 120000, confidenceLevel: "medium", monthsToRealize: 6, description: "More patients served with streamlined workflows" },
      { name: "Staff Productivity Gain", type: "productivity", annualValue: 72000, confidenceLevel: "medium", monthsToRealize: 4, description: "Less time on admin tasks, more on patient care" },
      { name: "Readmission Rate Reduction", type: "cost_reduction", annualValue: 50000, confidenceLevel: "low", monthsToRealize: 12, description: "Better care coordination reducing readmissions" },
    ],
  },
  {
    id: "logistics",
    name: "Logistics & Freight",
    industry: "logistics",
    description: "Trucking, fleet management, fuel, driver labor, and DOT compliance",
    costItems: [
      { name: "Current Fuel Costs", type: "opex", amount: 35000, frequency: "monthly", costPhase: "current_state", description: "Current diesel fuel expenditure for fleet" },
      { name: "Current Driver Wages", type: "opex", amount: 45000, frequency: "monthly", costPhase: "current_state", description: "Current driver wages, benefits, and per diem" },
      { name: "Current Truck Lease & Insurance", type: "opex", amount: 18000, frequency: "monthly", costPhase: "current_state", description: "Current truck lease payments, cargo and liability insurance" },
      { name: "Future Fuel Costs", type: "opex", amount: 28000, frequency: "monthly", costPhase: "future_state", description: "Reduced fuel spend via route optimization" },
      { name: "Future Driver Wages", type: "opex", amount: 42000, frequency: "monthly", costPhase: "future_state", description: "Optimized driver scheduling and utilization" },
      { name: "Future Truck Lease & Insurance", type: "escalating", amount: 16000, frequency: "monthly", escalationRate: 3, costPhase: "future_state", description: "Right-sized fleet with predictive maintenance reducing costs" },
      { name: "Fleet Management System", type: "capex", amount: 180000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "GPS tracking, telematics, and dispatch software" },
      { name: "DOT Compliance Upgrade", type: "one_time", amount: 45000, frequency: "once", costPhase: "project_cost", description: "ELD devices, safety systems, and drug testing program" },
      { name: "Driver Training Program", type: "transition", amount: 30000, frequency: "once", costPhase: "project_cost", description: "Safety and efficiency training rollout" },
    ],
    valueDrivers: [
      { name: "Fuel Efficiency Gain", type: "cost_reduction", annualValue: 84000, confidenceLevel: "high", monthsToRealize: 3, description: "Route optimization and driver behavior reducing fuel consumption" },
      { name: "Fleet Utilization Improvement", type: "productivity", annualValue: 120000, confidenceLevel: "medium", monthsToRealize: 6, description: "Higher loaded miles per truck through better dispatch" },
      { name: "Maintenance Cost Reduction", type: "cost_reduction", annualValue: 36000, confidenceLevel: "medium", monthsToRealize: 4, description: "Predictive maintenance avoiding costly breakdowns" },
      { name: "On-Time Delivery Premium", type: "revenue", annualValue: 60000, confidenceLevel: "low", monthsToRealize: 6, description: "Winning premium contracts through reliability improvements" },
    ],
  },
  {
    id: "banking",
    name: "Commercial Banking",
    industry: "banking",
    description: "Cost of funds, loan-loss provisions, compliance, branch operations, and core banking technology",
    costItems: [
      { name: "Current Cost of Funds", type: "opex", amount: 30000, frequency: "monthly", costPhase: "current_state", description: "Current interest paid on deposits and borrowings" },
      { name: "Current Loan-Loss Provision", type: "opex", amount: 15000, frequency: "monthly", costPhase: "current_state", description: "Current credit loss allowance and charge-off reserves" },
      { name: "Current Compliance & Branch Ops", type: "opex", amount: 25000, frequency: "monthly", costPhase: "current_state", description: "Current BSA/AML compliance, branch staff, and facility costs" },
      { name: "Future Cost of Funds", type: "opex", amount: 25000, frequency: "monthly", costPhase: "future_state", description: "Lower funding costs through digital deposit acquisition" },
      { name: "Future Loan-Loss Provision", type: "opex", amount: 10000, frequency: "monthly", costPhase: "future_state", description: "Reduced losses through improved credit scoring models" },
      { name: "Future Compliance & Branch Ops", type: "escalating", amount: 18000, frequency: "monthly", escalationRate: 4, costPhase: "future_state", description: "Automated compliance and optimized branch footprint" },
      { name: "Core Banking Migration", type: "capex", amount: 750000, frequency: "once", depreciationYears: 10, costPhase: "project_cost", description: "New core banking platform implementation" },
      { name: "Regulatory Reporting System", type: "capex", amount: 120000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "Automated regulatory reporting and compliance platform" },
      { name: "Staff Retraining", type: "transition", amount: 60000, frequency: "once", costPhase: "project_cost", description: "Training staff on new systems and processes" },
    ],
    valueDrivers: [
      { name: "Loan Processing Efficiency", type: "productivity", annualValue: 150000, confidenceLevel: "high", monthsToRealize: 6, description: "Faster underwriting and origination through automation" },
      { name: "Compliance Cost Reduction", type: "cost_reduction", annualValue: 48000, confidenceLevel: "medium", monthsToRealize: 4, description: "Automated BSA/AML monitoring reducing manual review" },
      { name: "Digital Channel Revenue", type: "revenue", annualValue: 200000, confidenceLevel: "medium", monthsToRealize: 9, description: "New fee income from digital banking products" },
      { name: "Fraud Loss Reduction", type: "cost_reduction", annualValue: 80000, confidenceLevel: "low", monthsToRealize: 6, description: "Better detection reducing fraudulent transaction losses" },
    ],
  },
  {
    id: "construction",
    name: "Construction",
    industry: "construction",
    description: "Subcontractor labor, materials, equipment rental, bonding, and project management",
    costItems: [
      { name: "Current Subcontractor Labor", type: "opex", amount: 60000, frequency: "monthly", costPhase: "current_state", description: "Current subcontractor and trade crew costs" },
      { name: "Current Materials & Supplies", type: "opex", amount: 40000, frequency: "monthly", costPhase: "current_state", description: "Current lumber, concrete, steel, and consumables" },
      { name: "Current Equipment Rental", type: "opex", amount: 15000, frequency: "monthly", costPhase: "current_state", description: "Current crane, excavator, and tool rental" },
      { name: "Future Subcontractor Labor", type: "opex", amount: 52000, frequency: "monthly", costPhase: "future_state", description: "Optimized crew scheduling and subcontractor mix" },
      { name: "Future Materials & Supplies", type: "opex", amount: 36000, frequency: "monthly", costPhase: "future_state", description: "Bulk procurement and waste reduction savings" },
      { name: "Future Equipment Costs", type: "escalating", amount: 12000, frequency: "monthly", escalationRate: 3, costPhase: "future_state", description: "Optimized equipment utilization across projects" },
      { name: "Project Management Software", type: "capex", amount: 85000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "BIM, scheduling, and construction management platform" },
      { name: "Bonding, Permits & Insurance", type: "one_time", amount: 40000, frequency: "once", costPhase: "project_cost", description: "Surety bonds, building permits, and contractor insurance" },
      { name: "Estimating System", type: "transition", amount: 35000, frequency: "once", costPhase: "project_cost", description: "Digital estimating and bid management platform" },
    ],
    valueDrivers: [
      { name: "Schedule Compression", type: "productivity", annualValue: 180000, confidenceLevel: "medium", monthsToRealize: 6, description: "Faster project delivery through better coordination" },
      { name: "Material Waste Reduction", type: "cost_reduction", annualValue: 72000, confidenceLevel: "high", monthsToRealize: 3, description: "Less waste through precise ordering and BIM clash detection" },
      { name: "Change Order Reduction", type: "cost_reduction", annualValue: 96000, confidenceLevel: "medium", monthsToRealize: 4, description: "Fewer costly rework items through better upfront planning" },
      { name: "Safety Incident Reduction", type: "cost_reduction", annualValue: 50000, confidenceLevel: "low", monthsToRealize: 6, description: "Lower workers comp and liability from improved safety programs" },
    ],
  },
  {
    id: "renewable_energy",
    name: "Renewable Energy",
    industry: "renewable_energy",
    description: "Solar/wind equipment, EPC construction, O&M, grid interconnection, and SCADA monitoring",
    costItems: [
      { name: "Current O&M Labor", type: "opex", amount: 18000, frequency: "monthly", costPhase: "current_state", description: "Current operations and maintenance field crew" },
      { name: "Current SCADA & Monitoring", type: "opex", amount: 5000, frequency: "monthly", costPhase: "current_state", description: "Current remote monitoring and control systems" },
      { name: "Current Land Lease", type: "opex", amount: 8000, frequency: "monthly", costPhase: "current_state", description: "Current land lease for existing generation assets" },
      { name: "Future O&M Labor", type: "opex", amount: 14000, frequency: "monthly", costPhase: "future_state", description: "Reduced O&M through predictive maintenance" },
      { name: "Future Monitoring Systems", type: "opex", amount: 3500, frequency: "monthly", costPhase: "future_state", description: "AI-driven automated monitoring reducing manual inspection" },
      { name: "Future Land Lease", type: "escalating", amount: 8500, frequency: "monthly", escalationRate: 2, costPhase: "future_state", description: "Land lease with annual escalation clause" },
      { name: "Solar/Wind Equipment", type: "capex", amount: 2000000, frequency: "once", depreciationYears: 25, costPhase: "project_cost", description: "Panels, inverters, turbines, and racking systems" },
      { name: "EPC Construction", type: "one_time", amount: 500000, frequency: "once", costPhase: "project_cost", description: "Engineering, procurement, and construction contract" },
      { name: "Grid Interconnection", type: "transition", amount: 150000, frequency: "once", costPhase: "project_cost", description: "Interconnection study, fees, and substation upgrades" },
    ],
    valueDrivers: [
      { name: "PPA Revenue", type: "revenue", annualValue: 480000, confidenceLevel: "high", monthsToRealize: 12, description: "Long-term power purchase agreement revenue stream" },
      { name: "REC & Tax Credit Income", type: "revenue", annualValue: 120000, confidenceLevel: "medium", monthsToRealize: 6, description: "Renewable energy certificates and production tax credits" },
      { name: "O&M Cost Reduction", type: "cost_reduction", annualValue: 66000, confidenceLevel: "medium", monthsToRealize: 4, description: "Predictive maintenance and remote monitoring savings" },
      { name: "Energy Storage Arbitrage", type: "revenue", annualValue: 80000, confidenceLevel: "low", monthsToRealize: 12, description: "Revenue from battery storage buy-low sell-high strategy" },
    ],
  },
  {
    id: "professional_services",
    name: "Professional Services",
    industry: "professional_services",
    description: "Consultant labor, travel, research tools, business development, and knowledge management",
    costItems: [
      { name: "Current Consultant Labor", type: "opex", amount: 50000, frequency: "monthly", costPhase: "current_state", description: "Current consultant and analyst salaries and benefits" },
      { name: "Current Travel & Lodging", type: "opex", amount: 12000, frequency: "monthly", costPhase: "current_state", description: "Current client-site travel and accommodation" },
      { name: "Current Research Subscriptions", type: "opex", amount: 6000, frequency: "monthly", costPhase: "current_state", description: "Current data tools, research platforms, and market intelligence" },
      { name: "Future Consultant Labor", type: "opex", amount: 45000, frequency: "monthly", costPhase: "future_state", description: "Optimized labor mix with junior/senior leverage" },
      { name: "Future Travel & Lodging", type: "opex", amount: 7000, frequency: "monthly", costPhase: "future_state", description: "Reduced travel through virtual delivery model" },
      { name: "Future Research & Tools", type: "escalating", amount: 5000, frequency: "monthly", escalationRate: 5, costPhase: "future_state", description: "Consolidated research platform subscriptions" },
      { name: "Knowledge Management System", type: "capex", amount: 120000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "Internal knowledge base and proposal library" },
      { name: "CRM & Business Dev Platform", type: "capex", amount: 60000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "Client relationship and pipeline management system" },
      { name: "Onboarding & Training Program", type: "transition", amount: 35000, frequency: "once", costPhase: "project_cost", description: "New hire training curriculum and mentorship program" },
    ],
    valueDrivers: [
      { name: "Utilization Rate Improvement", type: "productivity", annualValue: 180000, confidenceLevel: "high", monthsToRealize: 4, description: "Higher billable hours per consultant through better scheduling" },
      { name: "Travel Cost Reduction", type: "cost_reduction", annualValue: 60000, confidenceLevel: "high", monthsToRealize: 2, description: "Virtual delivery reducing client-site travel" },
      { name: "Proposal Win Rate Increase", type: "revenue", annualValue: 150000, confidenceLevel: "medium", monthsToRealize: 6, description: "Better proposals through knowledge reuse and templates" },
      { name: "Faster Onboarding", type: "productivity", annualValue: 40000, confidenceLevel: "medium", monthsToRealize: 3, description: "New hires productive sooner with structured training" },
    ],
  },
  {
    id: "ecommerce",
    name: "E-Commerce",
    industry: "ecommerce",
    description: "COGS, fulfillment, shipping, customer acquisition, returns, and platform costs",
    costItems: [
      { name: "Current COGS & Merchandise", type: "opex", amount: 80000, frequency: "monthly", costPhase: "current_state", description: "Current cost of goods sold and merchandise inventory" },
      { name: "Current Fulfillment & Shipping", type: "opex", amount: 25000, frequency: "monthly", costPhase: "current_state", description: "Current pick, pack, ship, and warehouse labor" },
      { name: "Current Customer Acquisition", type: "opex", amount: 20000, frequency: "monthly", costPhase: "current_state", description: "Current paid search, social, and affiliate spend" },
      { name: "Future COGS & Merchandise", type: "opex", amount: 72000, frequency: "monthly", costPhase: "future_state", description: "Improved margins through supplier negotiation and private label" },
      { name: "Future Fulfillment & Shipping", type: "opex", amount: 18000, frequency: "monthly", costPhase: "future_state", description: "3PL optimization and warehouse automation savings" },
      { name: "Future Customer Acquisition", type: "escalating", amount: 15000, frequency: "monthly", escalationRate: 5, costPhase: "future_state", description: "Lower CAC through better targeting and retention" },
      { name: "E-Commerce Platform", type: "capex", amount: 150000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "Headless commerce platform and storefront" },
      { name: "WMS Implementation", type: "one_time", amount: 80000, frequency: "once", costPhase: "project_cost", description: "Warehouse management system setup and integration" },
      { name: "Brand Launch Campaign", type: "transition", amount: 50000, frequency: "once", costPhase: "project_cost", description: "Initial marketing push and brand awareness campaign" },
    ],
    valueDrivers: [
      { name: "Conversion Rate Improvement", type: "revenue", annualValue: 120000, confidenceLevel: "medium", monthsToRealize: 4, description: "Better UX and product pages increasing purchase completion" },
      { name: "Fulfillment Cost Reduction", type: "cost_reduction", annualValue: 84000, confidenceLevel: "high", monthsToRealize: 3, description: "Automation and 3PL optimization reducing per-order cost" },
      { name: "Customer Lifetime Value Increase", type: "revenue", annualValue: 90000, confidenceLevel: "medium", monthsToRealize: 6, description: "Repeat purchase rate growth through loyalty programs" },
      { name: "Return Rate Reduction", type: "cost_reduction", annualValue: 36000, confidenceLevel: "low", monthsToRealize: 6, description: "Better product info reducing unnecessary returns" },
    ],
  },
  {
    id: "education",
    name: "Corporate Training",
    industry: "education",
    description: "Instructional design, LMS platform, facilitator labor, travel, and assessment tools",
    costItems: [
      { name: "Current Facilitator Labor", type: "opex", amount: 20000, frequency: "monthly", costPhase: "current_state", description: "Current trainer and facilitator salaries" },
      { name: "Current Travel & Logistics", type: "opex", amount: 10000, frequency: "monthly", costPhase: "current_state", description: "Current in-person delivery travel and venue costs" },
      { name: "Current LMS Subscription", type: "opex", amount: 4000, frequency: "monthly", costPhase: "current_state", description: "Current learning management system licensing" },
      { name: "Future Facilitator Labor", type: "opex", amount: 16000, frequency: "monthly", costPhase: "future_state", description: "Blended delivery model reducing live facilitation" },
      { name: "Future Travel & Logistics", type: "opex", amount: 4000, frequency: "monthly", costPhase: "future_state", description: "Virtual-first model dramatically reducing travel" },
      { name: "Future LMS & Tools", type: "escalating", amount: 5000, frequency: "monthly", escalationRate: 3, costPhase: "future_state", description: "Enhanced LMS with AI-driven adaptive learning" },
      { name: "LMS Platform Implementation", type: "capex", amount: 100000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "Enterprise LMS deployment and content migration" },
      { name: "Content Development", type: "one_time", amount: 75000, frequency: "once", costPhase: "project_cost", description: "Instructional design and e-learning module creation" },
      { name: "Pilot Cohort Rollout", type: "transition", amount: 25000, frequency: "once", costPhase: "project_cost", description: "Initial cohort training and feedback collection" },
    ],
    valueDrivers: [
      { name: "Training Delivery Cost Reduction", type: "cost_reduction", annualValue: 120000, confidenceLevel: "high", monthsToRealize: 3, description: "Virtual delivery eliminating travel and venue costs" },
      { name: "Employee Productivity Gain", type: "productivity", annualValue: 90000, confidenceLevel: "medium", monthsToRealize: 6, description: "Faster skill acquisition reducing time-to-competency" },
      { name: "Compliance Training Efficiency", type: "cost_reduction", annualValue: 40000, confidenceLevel: "high", monthsToRealize: 2, description: "Automated compliance tracking reducing admin overhead" },
      { name: "Employee Retention Improvement", type: "revenue", annualValue: 60000, confidenceLevel: "low", monthsToRealize: 12, description: "Better development programs reducing costly turnover" },
    ],
  },
];
