export const industryTemplates = [
  {
    id: "manufacturing",
    name: "Manufacturing",
    industry: "manufacturing",
    description: "Equipment, tooling, line changeover, maintenance, labor, and waste costs",
    costItems: [
      { name: "Current Direct Labor", type: "opex", amount: 15000, frequency: "monthly", costPhase: "current_state", description: "Current production floor labor costs" },
      { name: "Current Maintenance", type: "opex", amount: 5000, frequency: "monthly", costPhase: "current_state", description: "Current equipment maintenance costs" },
      { name: "Current Scrap & Waste", type: "opex", amount: 3000, frequency: "monthly", costPhase: "current_state", description: "Current material waste and scrap" },
      { name: "Future Direct Labor", type: "opex", amount: 12000, frequency: "monthly", costPhase: "future_state", description: "Optimized production floor labor costs" },
      { name: "Future Maintenance", type: "opex", amount: 4000, frequency: "monthly", costPhase: "future_state", description: "Reduced equipment maintenance costs" },
      { name: "Future Scrap & Waste", type: "opex", amount: 1500, frequency: "monthly", costPhase: "future_state", description: "Reduced material waste and scrap" },
      { name: "Equipment Purchase", type: "capex", amount: 500000, frequency: "once", depreciationYears: 10, costPhase: "project_cost", description: "Primary manufacturing equipment" },
      { name: "Tooling & Dies", type: "capex", amount: 75000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "Specialized tooling and dies" },
      { name: "Line Changeover", type: "transition", amount: 50000, frequency: "once", costPhase: "project_cost", description: "Production line reconfiguration" },
    ],
    valueDrivers: [
      { name: "Unit Cost Reduction", type: "cost_reduction", annualValue: 120000, confidenceLevel: "high", monthsToRealize: 3, description: "Lower per-unit production cost from automation" },
      { name: "Throughput / OEE Improvement", type: "productivity", annualValue: 200000, confidenceLevel: "medium", monthsToRealize: 6, description: "Increased output with same resources" },
      { name: "Scrap & Rework Reduction", type: "cost_reduction", annualValue: 36000, confidenceLevel: "high", monthsToRealize: 2, description: "Less material waste and fewer defective units" },
      { name: "Labor Productivity Gain", type: "productivity", annualValue: 80000, confidenceLevel: "medium", monthsToRealize: 4, description: "More output per labor hour" },
    ],
  },
  {
    id: "retail",
    name: "Retail",
    industry: "retail",
    description: "Inventory, shrinkage, store labor, POS systems, and logistics",
    costItems: [
      { name: "Current Store Labor", type: "opex", amount: 12000, frequency: "monthly", costPhase: "current_state", description: "Current retail staff wages" },
      { name: "Current Inventory Shrinkage", type: "opex", amount: 2500, frequency: "monthly", costPhase: "current_state", description: "Current theft, damage, admin errors" },
      { name: "Current Logistics", type: "opex", amount: 8000, frequency: "monthly", costPhase: "current_state", description: "Current distribution and delivery costs" },
      { name: "Future Store Labor", type: "opex", amount: 10000, frequency: "monthly", costPhase: "future_state", description: "Optimized retail staff wages" },
      { name: "Future Inventory Shrinkage", type: "opex", amount: 1200, frequency: "monthly", costPhase: "future_state", description: "Reduced shrinkage with new controls" },
      { name: "Future Logistics", type: "escalating", amount: 7000, frequency: "monthly", escalationRate: 4, costPhase: "future_state", description: "Optimized distribution costs" },
      { name: "Initial Inventory", type: "one_time", amount: 200000, frequency: "once", costPhase: "project_cost", description: "Initial stock purchase" },
      { name: "POS System", type: "capex", amount: 25000, frequency: "once", depreciationYears: 5, costPhase: "project_cost", description: "Point of sale hardware and software" },
      { name: "Store Setup", type: "transition", amount: 75000, frequency: "once", costPhase: "project_cost", description: "Store buildout and fixtures" },
    ],
    valueDrivers: [
      { name: "Shrinkage Reduction", type: "cost_reduction", annualValue: 30000, confidenceLevel: "high", monthsToRealize: 2, description: "Reduced inventory loss through better controls" },
      { name: "Inventory Turnover Improvement", type: "productivity", annualValue: 50000, confidenceLevel: "medium", monthsToRealize: 6, description: "Faster stock rotation and less dead inventory" },
      { name: "Conversion Rate Improvement", type: "revenue", annualValue: 80000, confidenceLevel: "medium", monthsToRealize: 4, description: "Higher percentage of visitors making purchases" },
      { name: "Average Basket Size Increase", type: "revenue", annualValue: 45000, confidenceLevel: "low", monthsToRealize: 6, description: "Upselling and cross-selling improvements" },
    ],
  },
  {
    id: "saas",
    name: "SaaS / Software",
    industry: "saas",
    description: "Licensing, infrastructure, implementation, training, and support",
    costItems: [
      { name: "Current Software Licensing", type: "opex", amount: 8000, frequency: "monthly", costPhase: "current_state", description: "Current legacy software subscription fees" },
      { name: "Current Cloud Infrastructure", type: "opex", amount: 4000, frequency: "monthly", costPhase: "current_state", description: "Current hosting and infrastructure costs" },
      { name: "Current Support Costs", type: "opex", amount: 3000, frequency: "monthly", costPhase: "current_state", description: "Current technical support burden" },
      { name: "Future Software Licensing", type: "opex", amount: 5000, frequency: "monthly", costPhase: "future_state", description: "New SaaS subscription fees" },
      { name: "Future Cloud Infrastructure", type: "opex", amount: 3000, frequency: "monthly", costPhase: "future_state", description: "Optimized hosting costs" },
      { name: "Future Support & Maintenance", type: "escalating", amount: 2000, frequency: "monthly", escalationRate: 5, costPhase: "future_state", description: "Ongoing technical support" },
      { name: "Implementation", type: "one_time", amount: 100000, frequency: "once", costPhase: "project_cost", description: "Initial setup and configuration" },
      { name: "Training", type: "transition", amount: 25000, frequency: "once", costPhase: "project_cost", description: "User training and onboarding" },
      { name: "Data Migration", type: "transition", amount: 30000, frequency: "once", costPhase: "project_cost", description: "Migration from legacy systems" },
    ],
    valueDrivers: [
      { name: "Customer Churn Reduction", type: "revenue", annualValue: 150000, confidenceLevel: "medium", monthsToRealize: 6, description: "Retaining more customers through better product experience" },
      { name: "CAC Improvement", type: "cost_reduction", annualValue: 60000, confidenceLevel: "medium", monthsToRealize: 4, description: "Lower customer acquisition cost through better tooling" },
      { name: "Support Ticket Deflection", type: "productivity", annualValue: 40000, confidenceLevel: "high", monthsToRealize: 3, description: "Self-service and automation reducing support volume" },
      { name: "Upsell / Expansion Revenue", type: "revenue", annualValue: 100000, confidenceLevel: "low", monthsToRealize: 9, description: "Increased revenue from existing customer base" },
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    industry: "healthcare",
    description: "Compliance, EHR systems, staffing, and regulatory filings",
    costItems: [
      { name: "Current Compliance & Audit", type: "opex", amount: 10000, frequency: "monthly", costPhase: "current_state", description: "Current HIPAA compliance and auditing costs" },
      { name: "Current Clinical Staffing", type: "opex", amount: 25000, frequency: "monthly", costPhase: "current_state", description: "Current healthcare professional wages" },
      { name: "Current Insurance Premiums", type: "opex", amount: 10000, frequency: "monthly", costPhase: "current_state", description: "Current malpractice and liability insurance" },
      { name: "Future Compliance & Audit", type: "opex", amount: 8000, frequency: "monthly", costPhase: "future_state", description: "Streamlined compliance with new EHR" },
      { name: "Future Clinical Staffing", type: "opex", amount: 22000, frequency: "monthly", costPhase: "future_state", description: "Optimized staffing with better tools" },
      { name: "Future Insurance Premiums", type: "escalating", amount: 9000, frequency: "monthly", escalationRate: 6, costPhase: "future_state", description: "Slightly reduced insurance costs" },
      { name: "EHR System", type: "capex", amount: 300000, frequency: "once", depreciationYears: 7, costPhase: "project_cost", description: "Electronic Health Records system" },
      { name: "Staff Training", type: "transition", amount: 40000, frequency: "once", costPhase: "project_cost", description: "Clinical staff training programs" },
      { name: "Regulatory Filings", type: "opex", amount: 5000, frequency: "annually", costPhase: "project_cost", description: "Annual regulatory submissions" },
    ],
    valueDrivers: [
      { name: "Billing Error Reduction", type: "cost_reduction", annualValue: 90000, confidenceLevel: "high", monthsToRealize: 3, description: "Fewer billing mistakes reducing revenue leakage" },
      { name: "Patient Throughput Increase", type: "revenue", annualValue: 120000, confidenceLevel: "medium", monthsToRealize: 6, description: "More patients served with streamlined workflows" },
      { name: "Staff Productivity Gain", type: "productivity", annualValue: 72000, confidenceLevel: "medium", monthsToRealize: 4, description: "Less time on admin tasks, more on patient care" },
      { name: "Readmission Rate Reduction", type: "cost_reduction", annualValue: 50000, confidenceLevel: "low", monthsToRealize: 12, description: "Better care coordination reducing readmissions" },
    ],
  },
];
